name: Test coverage report

on:
  pull_request:
    branches:
      - main
      - devlop
      - master

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: yarn ci
      - name: testing
        run: yarn test:ci
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.1
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
          annotations: none
          base-coverage-file: ./jest-report.json
          coverage-file: ./jest-report.json
